"""Initial migration

Revision ID: cd9549457171
Revises: 
Create Date: 2025-07-06 14:24:30.977544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9549457171'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_modes_id'), 'game_modes', ['id'], unique=False)
    op.create_index(op.f('ix_game_modes_name'), 'game_modes', ['name'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_sub_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'failed', 'completed', name='gamestatus'), nullable=False),
    sa.Column('mode_name', sa.String(), nullable=True),
    sa.Column('latency_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('correct_score', sa.Integer(), nullable=True),
    sa.Column('incorrect_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mode_name'], ['game_modes.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('question_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode_id', sa.Integer(), nullable=False),
    sa.Column('expression_type', sa.String(), nullable=True),
    sa.Column('expression_name', sa.String(), nullable=True),
    sa.Column('expression_difficulty', sa.Integer(), nullable=True),
    sa.Column('pitch', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mode_id'], ['game_modes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_types_expression_name'), 'question_types', ['expression_name'], unique=False)
    op.create_index(op.f('ix_question_types_expression_type'), 'question_types', ['expression_type'], unique=False)
    op.create_index(op.f('ix_question_types_id'), 'question_types', ['id'], unique=False)
    op.create_table('excellent_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excellent_recommendations_id'), 'excellent_recommendations', ['id'], unique=False)
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answered_questions_collected', sa.JSON(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_id'), 'stats', ['id'], unique=False)
    op.create_table('training_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_recommendations_id'), 'training_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_recommendations_id'), table_name='training_recommendations')
    op.drop_table('training_recommendations')
    op.drop_index(op.f('ix_stats_id'), table_name='stats')
    op.drop_table('stats')
    op.drop_index(op.f('ix_excellent_recommendations_id'), table_name='excellent_recommendations')
    op.drop_table('excellent_recommendations')
    op.drop_index(op.f('ix_question_types_id'), table_name='question_types')
    op.drop_index(op.f('ix_question_types_expression_type'), table_name='question_types')
    op.drop_index(op.f('ix_question_types_expression_name'), table_name='question_types')
    op.drop_table('question_types')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_game_modes_name'), table_name='game_modes')
    op.drop_index(op.f('ix_game_modes_id'), table_name='game_modes')
    op.drop_table('game_modes')
    # ### end Alembic commands ###
